2022-07-05 19:41:25,460 - INFO - Instabot Started
2022-07-05 19:41:56,641 - INFO - PRE-LOGIN FLOW!... 
2022-07-05 19:41:56,660 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/read_msisdn_header/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026BC75FEFB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-07-05 19:41:56,665 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/launcher/sync/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026BC75FF040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-07-05 19:41:56,673 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/sync/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026BC75FF100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-07-05 19:41:56,679 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/attribution/log_attribution/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026BC75FF1F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
