2022-07-05 19:40:17,296 - INFO - Instabot Started
2022-07-05 19:41:12,150 - INFO - PRE-LOGIN FLOW!... 
2022-07-05 19:41:12,163 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/read_msisdn_header/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D905DBEFB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-07-05 19:41:12,167 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/launcher/sync/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D905DBF040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-07-05 19:41:12,172 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/sync/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D905DBF100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-07-05 19:41:12,180 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/attribution/log_attribution/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D905DBF1F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
