2022-07-05 19:37:56,034 - INFO - Instabot Started
2022-07-05 19:40:09,915 - INFO - PRE-LOGIN FLOW!... 
2022-07-05 19:40:09,932 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/read_msisdn_header/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002492D20EFB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-07-05 19:40:09,937 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/launcher/sync/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002492D20F040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-07-05 19:40:09,947 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/sync/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002492D20F100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-07-05 19:40:09,954 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/attribution/log_attribution/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002492D20F1F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
